name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run maven script
        uses: xlui/action-maven-cli/jdk11@master
        id: test
        with:
          lifecycle: 'clean test'